### ISSUE TITLE
npm not working

### ISSUE THREAD

**Issue by Nishant5454** [moviemultiverse/core#3]
I have installed all the Packages on vs code ..but when i run npm run dev local host link is not working

**Comment by SS0809** [comment]
sorry for inconvenience , 
```npx nodemon index.js``` this might work

**Comment by SS0809** [comment]
i will be updating documentation soon ,
hope this issue is resolved.

**Comment by Nishant5454** [comment]
Still it is not running on the terminal..it showing folder is Depricated
