### ISSUE TITLE
Pagination Issue

### ISSUE THREAD

**Issue by SS0809** [moviemultiverse/core#7]
allMovieNames graphql endpoint returns lots of data ,
which obviously applications does not support .

**Comment by KunalSin9h** [comment]
@SS0809 graphql always return lots of data, you have to choose what data you want to get, so just send the `query` of what data you want and it will send only that data.

**Comment by SS0809** [comment]
> @SS0809 graphql always return lots of data, you have to choose what data you want to get, so just send the `query` of what data you want and it will send only that data.

That's the reason this issue is opened , need to optimise the `query`

**Comment by KunalSin9h** [comment]
which query you are currently using?

**Comment by SS0809** [comment]
> which query you are currently using?

thanks for your interest in the issue :)

[commit](https://github.com/SS0809/core/commit/811f92d45552e609af1a9c63b37d95af59911510)

**Comment by KunalSin9h** [comment]
this is the whole data. 
what data you want?
![image](https://github.com/moviemultiverse/core/assets/82411321/31370181-20bc-46bb-84a4-1bb9c652f524)

**Comment by KunalSin9h** [comment]
@SS0809 i dont think its graphql endpoint, as it gives the response using just `GET` Http.

**Comment by KunalSin9h** [comment]
go to get the data you want, just fetch it and use `res.json()` and unpack into a struct and use data you want.
```js
const res = await fetch("that url here");
const data = await res.json();

// data is array 

for (let d of data) {
   console.log(d.file_name)
}
```

**Comment by SS0809** [comment]
> @SS0809 i dont think its graphql endpoint, as it gives the response using just `GET` Http.

that wasn't graphql endpoint.. it was for other module .

graphql endpoint has been updated in that commit only, 
and it's working fine 

```
-> added limit , and offset parameters to the query
```

**Comment by SS0809** [comment]
# Before parameters
![image](https://github.com/moviemultiverse/core/assets/94746927/af75edb2-a95b-4ab1-9cd3-ee14d23f4690)

# After Parameters
## without params
![image](https://github.com/moviemultiverse/core/assets/94746927/8a73d6f9-d6e2-40b9-a8e6-f82789dcf118)
## with params
![image](https://github.com/moviemultiverse/core/assets/94746927/9219914c-9c36-4b55-a69f-0ed90d8f5d15)

## Conclusion 
_> it allows android client to request with and without params to the endpoint
